/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/kalka/mnt/backup_19.3.gltf -t 
*/

import * as THREE from 'three'
import React, { JSX, useEffect } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useAtom } from 'jotai'
import { modelReadyAtom } from '@/lib/atom'

type ActionName =
  | 'confused_start'
  | 'confused_end'
  | 'blink'
  | 'beep_boop'
  | 'annoyed_face'
  | 'happy_face'
  | 'sleeping'
  | 'idling'
  | 'sleeping_manual'
  | 'advanced_blink'
  | 'advanced_blink_loop'
  | '_jumpingup'
  | 'falling'
  | 'flying'
  | 'fall_end'
  | '_jumpingdown'
  | 'talk'
  | 'sitting_start'
  | 'sitting'
  | 'wave'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Ear: THREE.Mesh
    Ear_1: THREE.Mesh
    Ear_2: THREE.Mesh
    Ear_3: THREE.Mesh
    Visor_Lid: THREE.Mesh
    Visor_Lid_1: THREE.Mesh
    Visor_Lid_2: THREE.Mesh
    Visor_Lid_3: THREE.Mesh
    Visor_Lid_4: THREE.Mesh
    Visor_Lid_5: THREE.Mesh
    Visor_Mouth: THREE.Mesh
    Visor_Mouth_1: THREE.Mesh
    Visor_Lid_6: THREE.Mesh
    Visor_Lid_7: THREE.Mesh
    Visor_Lid_8: THREE.Mesh
    Visor_Lid_9: THREE.Mesh
    Visor: THREE.Mesh
    ['Visor_(bak2)']: THREE.Mesh
    ['Visor_(bak)']: THREE.Mesh
    Visor_1: THREE.Mesh
    Visor_2: THREE.Mesh
    Visor_3: THREE.Mesh
    Neck: THREE.Mesh
    Head_1: THREE.Mesh
    Screw: THREE.Mesh
    Screw_1: THREE.Mesh
    Separator: THREE.Mesh
    Fur: THREE.Mesh
    Fur_1: THREE.Mesh
    Fur_2: THREE.Mesh
    Fur_3: THREE.Mesh
    Tail_5: THREE.Mesh
    Tail_4: THREE.Mesh
    Tail_3: THREE.Mesh
    Tail_2: THREE.Mesh
    Tail_1: THREE.Mesh
    Panel: THREE.Mesh
    cube: THREE.Mesh
    cube_1: THREE.Mesh
    cube_2: THREE.Mesh
    cube_3: THREE.Mesh
    cube_4: THREE.Mesh
    cube_5: THREE.Mesh
    ['Panel_(bak)']: THREE.Mesh
    Back_Panel: THREE.Mesh
    Hips: THREE.Mesh
    Chest: THREE.Mesh
    Waist: THREE.Mesh
    Right_Arm: THREE.Mesh
    Shield: THREE.Mesh
    Shield_1: THREE.Mesh
    Shield_2: THREE.Mesh
    Shield_3: THREE.Mesh
    Shield_Panel: THREE.Mesh
    Shield_4: THREE.Mesh
    Shield_5: THREE.Mesh
    Shield_Panel_1: THREE.Mesh
    Shield_6: THREE.Mesh
    Shield_Panel_2: THREE.Mesh
    Shield_7: THREE.Mesh
    Left_Arm: THREE.Mesh
    Shield_8: THREE.Mesh
    Shield_9: THREE.Mesh
    Shield_10: THREE.Mesh
    Shield_11: THREE.Mesh
    Shield_Panel_3: THREE.Mesh
    Shield_12: THREE.Mesh
    Shield_13: THREE.Mesh
    Shield_14: THREE.Mesh
    Shield_Panel_4: THREE.Mesh
    Shield_15: THREE.Mesh
    Shield_16: THREE.Mesh
    Shield_17: THREE.Mesh
    Shield_Panel_5: THREE.Mesh
    Right_Leg: THREE.Mesh
    Right_Leg_Shield_Bracket_Plate: THREE.Mesh
    Right_Leg_Shield_Bracket_Plate_2: THREE.Mesh
    Right_Leg_Shield_Bracket_Plate_3: THREE.Mesh
    Right_Leg_Shield_Bracket_Plate_4: THREE.Mesh
    Right_Leg_Shield: THREE.Mesh
    Right_Leg_Shield_Bracket: THREE.Mesh
    Right_Leg_Shield_Bracket_2: THREE.Mesh
    Right_Leg_Shield_Bracket_3: THREE.Mesh
    Right_Leg_Shield_Bracket_4: THREE.Mesh
    Right_Leg_2: THREE.Mesh
    Right_Leg_3: THREE.Mesh
    Right_Foot_1: THREE.Mesh
    Cape_1: THREE.Mesh
    Left_Leg: THREE.Mesh
    Left_Leg_Shield: THREE.Mesh
    Left_Leg_Shield_Bracket: THREE.Mesh
    Left_Leg_Shield_Bracket_2: THREE.Mesh
    Left_Leg_Shield_Bracket_3: THREE.Mesh
    Left_Leg_Shield_Bracket_4: THREE.Mesh
    Left_Leg_Shield_Bracket_Plate: THREE.Mesh
    Left_Leg_Shield_Bracket_Plate_2: THREE.Mesh
    Left_Leg_Shield_Bracket_Plate_3: THREE.Mesh
    Left_Leg_Shield_Bracket_Plate_4: THREE.Mesh
    Left_Leg_2: THREE.Mesh
    Left_Leg_3: THREE.Mesh
    Left_Foot_1: THREE.Mesh
  }
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  materials: {}
  animations: GLTFAction[]
}

function KalkaProtogenModel(props: Readonly<JSX.IntrinsicElements['group']>) {
  const [, setModelReady] = useAtom(modelReadyAtom)
  const group = React.useRef<THREE.Group>(null)
  const { nodes, animations } = useGLTF('/proot.gltf') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    let action = actions['wave'] // Change to the animation you want
    if (action) {
      action.reset().play()
      action.clampWhenFinished = true
      action.loop = THREE.LoopOnce
    }

    action = actions['advanced_blink_loop']

    if (action) {
      action.reset().play()
      action.clampWhenFinished = true
      action.loop = THREE.LoopRepeat
    }

    action = actions['beep_boop']

    if (action) {
      action.reset().play()
      action.clampWhenFinished = true
      action.loop = THREE.LoopRepeat
    }

    action = actions['idling']

    if (action) {
      action.reset().play()
      action.clampWhenFinished = true
      action.loop = THREE.LoopRepeat
    }
  }, [actions])

  useThree((state) => {
    state.camera.position.set(0.5, 2, -0.9)
    state.camera.lookAt(0, 1.5, 0)

    // Ensure the camera updates
    state.camera.updateProjectionMatrix()

    setModelReady(true)

    //state.camera.rotateOnAxis(new Vector3(0, 1.8, 0), 180)
  })

  useFrame(() => {})

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="blockbench_export">
        <group>
          <group name="Main">
            <group name="Head" position={[0, 1.5, 0]}>
              <group name="LeftEar" position={[0, 0.219, 0]}>
                <mesh
                  name="Ear"
                  geometry={nodes.Ear.geometry}
                  material={nodes.Ear.material}
                  rotation={[-0.401, -0.201, -0.085]}
                />
                <mesh
                  name="Ear_1"
                  geometry={nodes.Ear_1.geometry}
                  material={nodes.Ear_1.material}
                  rotation={[-0.401, -0.201, -0.085]}
                />
              </group>
              <group name="RightEar" position={[0, 0.219, 0]}>
                <mesh
                  name="Ear_2"
                  geometry={nodes.Ear_2.geometry}
                  material={nodes.Ear_2.material}
                  rotation={[-0.401, 0.201, 0.085]}
                />
                <mesh
                  name="Ear_3"
                  geometry={nodes.Ear_3.geometry}
                  material={nodes.Ear_3.material}
                  rotation={[-0.401, 0.201, 0.085]}
                />
              </group>
              <group
                name="VisorTop"
                position={[0, 0.063, -0.375]}
                rotation={[-0.305, 0, 0]}
              >
                <group name="Visor_Half_Lid_Left">
                  <mesh
                    name="Visor_Lid"
                    geometry={nodes.Visor_Lid.geometry}
                    material={nodes.Visor_Lid.material}
                    position={[0.125, 0, 0]}
                    rotation={[0, 0.218, 0]}
                  />
                </group>
                <group name="Visor_Half_Lid_Right">
                  <mesh
                    name="Visor_Lid_1"
                    geometry={nodes.Visor_Lid_1.geometry}
                    material={nodes.Visor_Lid_1.material}
                    position={[-0.125, 0, 0]}
                    rotation={[0, -0.218, 0]}
                  />
                </group>
                <group name="Visor_Lid_Left">
                  <mesh
                    name="Visor_Lid_2"
                    geometry={nodes.Visor_Lid_2.geometry}
                    material={nodes.Visor_Lid_2.material}
                    position={[-0.125, 0, 0]}
                    rotation={[0, -0.218, 0]}
                  />
                </group>
                <group name="Visor_Lid_Right">
                  <mesh
                    name="Visor_Lid_3"
                    geometry={nodes.Visor_Lid_3.geometry}
                    material={nodes.Visor_Lid_3.material}
                    position={[0.125, 0, 0]}
                    rotation={[0, 0.218, 0]}
                  />
                </group>
                <group name="Visor_Eye_Annoyed_Left">
                  <mesh
                    name="Visor_Lid_4"
                    geometry={nodes.Visor_Lid_4.geometry}
                    material={nodes.Visor_Lid_4.material}
                    position={[-0.125, 0, 0]}
                    rotation={[0, -0.218, 0]}
                  />
                </group>
                <group name="Visor_Eye_Annoyed_Right">
                  <mesh
                    name="Visor_Lid_5"
                    geometry={nodes.Visor_Lid_5.geometry}
                    material={nodes.Visor_Lid_5.material}
                    position={[0.125, 0, 0]}
                    rotation={[0, 0.218, 0]}
                  />
                </group>
                <group name="Visor_Mouth_Annoyed_Left">
                  <mesh
                    name="Visor_Mouth"
                    geometry={nodes.Visor_Mouth.geometry}
                    material={nodes.Visor_Mouth.material}
                    position={[-0.125, 0, 0]}
                    rotation={[0, -0.218, 0]}
                  />
                </group>
                <group name="Visor_Mouth_Annoyed_Right">
                  <mesh
                    name="Visor_Mouth_1"
                    geometry={nodes.Visor_Mouth_1.geometry}
                    material={nodes.Visor_Mouth_1.material}
                    position={[0.125, 0, 0]}
                    rotation={[0, 0.218, 0]}
                  />
                </group>
                <group name="Visor_Eye_Happy_Left">
                  <mesh
                    name="Visor_Lid_6"
                    geometry={nodes.Visor_Lid_6.geometry}
                    material={nodes.Visor_Lid_6.material}
                    position={[-0.125, 0, 0]}
                    rotation={[0, -0.218, 0]}
                  />
                  <mesh
                    name="Visor_Lid_7"
                    geometry={nodes.Visor_Lid_7.geometry}
                    material={nodes.Visor_Lid_7.material}
                    position={[-0.125, 0, 0]}
                    rotation={[0, -0.218, 0]}
                  />
                </group>
                <group name="Visor_Eye_Happy_Right">
                  <mesh
                    name="Visor_Lid_8"
                    geometry={nodes.Visor_Lid_8.geometry}
                    material={nodes.Visor_Lid_8.material}
                    position={[0.125, 0, 0]}
                    rotation={[0, 0.218, 0]}
                  />
                  <mesh
                    name="Visor_Lid_9"
                    geometry={nodes.Visor_Lid_9.geometry}
                    material={nodes.Visor_Lid_9.material}
                    position={[0.125, 0, 0]}
                    rotation={[0, 0.218, 0]}
                  />
                </group>
                <mesh
                  name="Visor"
                  geometry={nodes.Visor.geometry}
                  material={nodes.Visor.material}
                  position={[0, -1.563, 0.375]}
                />
                <mesh
                  name="Visor_(bak2)"
                  geometry={nodes['Visor_(bak2)'].geometry}
                  material={nodes['Visor_(bak2)'].material}
                  position={[0.125, 0, 0]}
                  rotation={[0, 0.218, 0]}
                />
                <mesh
                  name="Visor_(bak)"
                  geometry={nodes['Visor_(bak)'].geometry}
                  material={nodes['Visor_(bak)'].material}
                  position={[-0.125, 0, 0]}
                  rotation={[0, -0.218, 0]}
                />
              </group>
              <group name="VisorBottom" position={[0, 0.063, -0.375]}>
                <mesh
                  name="Visor_1"
                  geometry={nodes.Visor_1.geometry}
                  material={nodes.Visor_1.material}
                  position={[-0.125, 0, 0]}
                  rotation={[0, -0.218, 0]}
                />
                <mesh
                  name="Visor_2"
                  geometry={nodes.Visor_2.geometry}
                  material={nodes.Visor_2.material}
                  position={[0.125, 0, 0]}
                  rotation={[0, 0.218, 0]}
                />
                <mesh
                  name="Visor_3"
                  geometry={nodes.Visor_3.geometry}
                  material={nodes.Visor_3.material}
                  position={[0, -1.563, 0.375]}
                />
              </group>
              <mesh
                name="Neck"
                geometry={nodes.Neck.geometry}
                material={nodes.Neck.material}
                position={[0, -1.5, 0]}
              />
              <mesh
                name="Head_1"
                geometry={nodes.Head_1.geometry}
                material={nodes.Head_1.material}
                position={[0, -1.5, 0]}
              />
              <mesh
                name="Screw"
                geometry={nodes.Screw.geometry}
                material={nodes.Screw.material}
                position={[-0.219, 0.156, 0.031]}
                rotation={[-Math.PI / 4, 0, 0]}
              />
              <mesh
                name="Screw_1"
                geometry={nodes.Screw_1.geometry}
                material={nodes.Screw_1.material}
                position={[-0.219, 0.156, 0.031]}
                rotation={[-Math.PI / 4, 0, 0]}
              />
              <mesh
                name="Separator"
                geometry={nodes.Separator.geometry}
                material={nodes.Separator.material}
                position={[0, 0.219, 0]}
                rotation={[-0.262, 0, 0]}
              />
              <mesh
                name="Fur"
                geometry={nodes.Fur.geometry}
                material={nodes.Fur.material}
                rotation={[-0.175, 0, 0]}
              />
              <mesh
                name="Fur_1"
                geometry={nodes.Fur_1.geometry}
                material={nodes.Fur_1.material}
                rotation={[0.087, 0, 0]}
              />
              <mesh
                name="Fur_2"
                geometry={nodes.Fur_2.geometry}
                material={nodes.Fur_2.material}
                rotation={[0.611, 0, 0]}
              />
              <mesh
                name="Fur_3"
                geometry={nodes.Fur_3.geometry}
                material={nodes.Fur_3.material}
                rotation={[1.004, 0, 0]}
              />
            </group>
            <group name="Body" position={[0, 1.5, 0]}>
              <group
                name="Tail"
                position={[0, -0.563, 0]}
                rotation={[Math.PI / 3, 0, 0]}
              >
                <group name="Tail1" position={[0, 0.031, 0.219]}>
                  <group
                    name="Tail2"
                    position={[0, -0.021, 0.32]}
                    rotation={[-0.262, 0, 0]}
                  >
                    <group
                      name="Tail3"
                      position={[0, -0.003, 0.311]}
                      rotation={[-0.131, 0, 0]}
                    >
                      <group
                        name="Tail4"
                        position={[0, 0.036, 0.291]}
                        rotation={[-0.087, 0, 0]}
                      >
                        <group
                          name="tailLocator"
                          position={[0, 0.065, 0.177]}
                          rotation={[0.48, 0, 0]}
                        >
                          <group name="tailLocator_1" scale={0.014} />
                        </group>
                        <mesh
                          name="Tail_5"
                          geometry={nodes.Tail_5.geometry}
                          material={nodes.Tail_5.material}
                          position={[0, 0.11, 0.079]}
                          rotation={[-0.48, 0, 0]}
                        />
                      </group>
                      <mesh
                        name="Tail_4"
                        geometry={nodes.Tail_4.geometry}
                        material={nodes.Tail_4.material}
                        position={[0, 0.094, 0.15]}
                        rotation={[-0.131, 0, 0]}
                      />
                    </group>
                    <mesh
                      name="Tail_3"
                      geometry={nodes.Tail_3.geometry}
                      material={nodes.Tail_3.material}
                      position={[0, -0.948, -0.539]}
                    />
                  </group>
                  <mesh
                    name="Tail_2"
                    geometry={nodes.Tail_2.geometry}
                    material={nodes.Tail_2.material}
                    position={[0, -0.969, -0.219]}
                  />
                </group>
                <mesh
                  name="Tail_1"
                  geometry={nodes.Tail_1.geometry}
                  material={nodes.Tail_1.material}
                  position={[0, -0.938, 0]}
                />
              </group>
              <group name="ChestPlate">
                <group name="ChestPlatePanel">
                  <mesh
                    name="Panel"
                    geometry={nodes.Panel.geometry}
                    material={nodes.Panel.material}
                    position={[0, -1.5, 0]}
                  />
                </group>
                <group name="Front" position={[0, -1.5, 0]}>
                  <mesh
                    name="cube"
                    geometry={nodes.cube.geometry}
                    material={nodes.cube.material}
                  />
                  <mesh
                    name="cube_1"
                    geometry={nodes.cube_1.geometry}
                    material={nodes.cube_1.material}
                  />
                  <mesh
                    name="cube_2"
                    geometry={nodes.cube_2.geometry}
                    material={nodes.cube_2.material}
                  />
                  <mesh
                    name="cube_3"
                    geometry={nodes.cube_3.geometry}
                    material={nodes.cube_3.material}
                  />
                  <mesh
                    name="cube_4"
                    geometry={nodes.cube_4.geometry}
                    material={nodes.cube_4.material}
                  />
                  <mesh
                    name="cube_5"
                    geometry={nodes.cube_5.geometry}
                    material={nodes.cube_5.material}
                  />
                </group>
                <mesh
                  name="Panel_(bak)"
                  geometry={nodes['Panel_(bak)'].geometry}
                  material={nodes['Panel_(bak)'].material}
                  position={[0, -1.5, 0]}
                />
                <mesh
                  name="Back_Panel"
                  geometry={nodes.Back_Panel.geometry}
                  material={nodes.Back_Panel.material}
                  position={[0, -1.5, 0]}
                />
              </group>
              <mesh
                name="Waist"
                geometry={nodes.Waist.geometry}
                material={nodes.Waist.material}
                position={[0, -1.5, 0]}
              />
              <mesh
                name="Chest"
                geometry={nodes.Chest.geometry}
                material={nodes.Chest.material}
                position={[0, -1.5, 0]}
              />
              <mesh
                name="Hips"
                geometry={nodes.Hips.geometry}
                material={nodes.Hips.material}
                position={[0, -1.5, 0]}
              />
            </group>
            <group name="RightArm" position={[0.313, 1.375, 0]}>
              <group name="RightItemPivot" position={[0.031, -0.625, -0.125]} />
              <mesh
                name="Right_Arm"
                geometry={nodes.Right_Arm.geometry}
                material={nodes.Right_Arm.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield"
                geometry={nodes.Shield.geometry}
                material={nodes.Shield.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_1"
                geometry={nodes.Shield_1.geometry}
                material={nodes.Shield_1.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_2"
                geometry={nodes.Shield_2.geometry}
                material={nodes.Shield_2.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_3"
                geometry={nodes.Shield_3.geometry}
                material={nodes.Shield_3.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_Panel"
                geometry={nodes.Shield_Panel.geometry}
                material={nodes.Shield_Panel.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_4"
                geometry={nodes.Shield_4.geometry}
                material={nodes.Shield_4.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_5"
                geometry={nodes.Shield_5.geometry}
                material={nodes.Shield_5.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_Panel_1"
                geometry={nodes.Shield_Panel_1.geometry}
                material={nodes.Shield_Panel_1.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_6"
                geometry={nodes.Shield_6.geometry}
                material={nodes.Shield_6.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_Panel_2"
                geometry={nodes.Shield_Panel_2.geometry}
                material={nodes.Shield_Panel_2.material}
                position={[-0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_7"
                geometry={nodes.Shield_7.geometry}
                material={nodes.Shield_7.material}
                position={[-0.313, -1.375, 0]}
              />
            </group>
            <group name="LeftArm" position={[-0.313, 1.375, 0]}>
              <group name="LeftItemPivot" position={[-0.031, -0.625, -0.125]} />
              <mesh
                name="Left_Arm"
                geometry={nodes.Left_Arm.geometry}
                material={nodes.Left_Arm.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_8"
                geometry={nodes.Shield_8.geometry}
                material={nodes.Shield_8.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_9"
                geometry={nodes.Shield_9.geometry}
                material={nodes.Shield_9.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_10"
                geometry={nodes.Shield_10.geometry}
                material={nodes.Shield_10.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_11"
                geometry={nodes.Shield_11.geometry}
                material={nodes.Shield_11.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_Panel_3"
                geometry={nodes.Shield_Panel_3.geometry}
                material={nodes.Shield_Panel_3.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_12"
                geometry={nodes.Shield_12.geometry}
                material={nodes.Shield_12.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_13"
                geometry={nodes.Shield_13.geometry}
                material={nodes.Shield_13.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_14"
                geometry={nodes.Shield_14.geometry}
                material={nodes.Shield_14.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_Panel_4"
                geometry={nodes.Shield_Panel_4.geometry}
                material={nodes.Shield_Panel_4.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_15"
                geometry={nodes.Shield_15.geometry}
                material={nodes.Shield_15.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_16"
                geometry={nodes.Shield_16.geometry}
                material={nodes.Shield_16.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_17"
                geometry={nodes.Shield_17.geometry}
                material={nodes.Shield_17.material}
                position={[0.313, -1.375, 0]}
              />
              <mesh
                name="Shield_Panel_5"
                geometry={nodes.Shield_Panel_5.geometry}
                material={nodes.Shield_Panel_5.material}
                position={[0.313, -1.375, 0]}
              />
            </group>
            <group name="RightLeg" position={[0.119, 0.75, 0]}>
              <group name="Upper_Right_Leg">
                <mesh
                  name="Right_Leg"
                  geometry={nodes.Right_Leg.geometry}
                  material={nodes.Right_Leg.material}
                  position={[-0.119, -0.75, 0]}
                  rotation={[0.42, -0.08, 0.036]}
                />
                <mesh
                  name="Right_Leg_Shield_Bracket_Plate"
                  geometry={nodes.Right_Leg_Shield_Bracket_Plate.geometry}
                  material={nodes.Right_Leg_Shield_Bracket_Plate.material}
                  position={[-0.119, -0.75, 0]}
                  rotation={[0.42, -0.08, 0.036]}
                />
                <mesh
                  name="Right_Leg_Shield_Bracket_Plate_2"
                  geometry={nodes.Right_Leg_Shield_Bracket_Plate_2.geometry}
                  material={nodes.Right_Leg_Shield_Bracket_Plate_2.material}
                  position={[-0.119, -0.75, 0]}
                  rotation={[0.42, -0.08, 0.036]}
                />
                <mesh
                  name="Right_Leg_Shield_Bracket_Plate_3"
                  geometry={nodes.Right_Leg_Shield_Bracket_Plate_3.geometry}
                  material={nodes.Right_Leg_Shield_Bracket_Plate_3.material}
                  position={[-0.119, -0.75, 0]}
                  rotation={[0.42, -0.08, 0.036]}
                />
                <mesh
                  name="Right_Leg_Shield_Bracket_Plate_4"
                  geometry={nodes.Right_Leg_Shield_Bracket_Plate_4.geometry}
                  material={nodes.Right_Leg_Shield_Bracket_Plate_4.material}
                  position={[-0.119, -0.75, 0]}
                  rotation={[0.42, -0.08, 0.036]}
                />
                <mesh
                  name="Right_Leg_Shield"
                  geometry={nodes.Right_Leg_Shield.geometry}
                  material={nodes.Right_Leg_Shield.material}
                  position={[-0.119, -0.75, 0]}
                  rotation={[0.42, -0.08, 0.036]}
                />
                <mesh
                  name="Right_Leg_Shield_Bracket"
                  geometry={nodes.Right_Leg_Shield_Bracket.geometry}
                  material={nodes.Right_Leg_Shield_Bracket.material}
                  position={[-0.119, -0.75, 0]}
                  rotation={[0.42, -0.08, 0.036]}
                />
                <mesh
                  name="Right_Leg_Shield_Bracket_2"
                  geometry={nodes.Right_Leg_Shield_Bracket_2.geometry}
                  material={nodes.Right_Leg_Shield_Bracket_2.material}
                  position={[-0.119, -0.75, 0]}
                  rotation={[0.42, -0.08, 0.036]}
                />
                <mesh
                  name="Right_Leg_Shield_Bracket_3"
                  geometry={nodes.Right_Leg_Shield_Bracket_3.geometry}
                  material={nodes.Right_Leg_Shield_Bracket_3.material}
                  position={[-0.119, -0.75, 0]}
                  rotation={[0.42, -0.08, 0.036]}
                />
                <mesh
                  name="Right_Leg_Shield_Bracket_4"
                  geometry={nodes.Right_Leg_Shield_Bracket_4.geometry}
                  material={nodes.Right_Leg_Shield_Bracket_4.material}
                  position={[-0.119, -0.75, 0]}
                  rotation={[0.42, -0.08, 0.036]}
                />
              </group>
              <group name="Lower_Right_Leg" position={[-0.119, -0.75, 0]}>
                <group name="Lower_Right_Leg_2">
                  <mesh
                    name="Right_Leg_2"
                    geometry={nodes.Right_Leg_2.geometry}
                    material={nodes.Right_Leg_2.material}
                    rotation={[-0.962, -0.05, -0.072]}
                  />
                </group>
                <group name="Lower_Right_Leg_3">
                  <mesh
                    name="Right_Leg_3"
                    geometry={nodes.Right_Leg_3.geometry}
                    material={nodes.Right_Leg_3.material}
                    rotation={[0.131, -0.087, 0.011]}
                  />
                </group>
                <group name="Right_Foot">
                  <group name="rightFootLocator" position={[0, 0, -0.219]}>
                    <group name="rightFootLocator_1" scale={0.014} />
                  </group>
                  <mesh
                    name="Right_Foot_1"
                    geometry={nodes.Right_Foot_1.geometry}
                    material={nodes.Right_Foot_1.material}
                    rotation={[0, -0.087, 0]}
                  />
                </group>
              </group>
            </group>
            <group name="Cape" position={[0, 1.5, 0.125]}>
              <mesh
                name="Cape_1"
                geometry={nodes.Cape_1.geometry}
                material={nodes.Cape_1.material}
                rotation={[-Math.PI / 9, 0, 0]}
              />
            </group>
            <group name="LeftLeg" position={[-0.119, 0.75, 0]}>
              <group name="Upper_Left_Leg">
                <mesh
                  name="Left_Leg"
                  geometry={nodes.Left_Leg.geometry}
                  material={nodes.Left_Leg.material}
                  position={[0.119, -0.75, 0]}
                  rotation={[0.42, 0.08, -0.036]}
                />
                <mesh
                  name="Left_Leg_Shield"
                  geometry={nodes.Left_Leg_Shield.geometry}
                  material={nodes.Left_Leg_Shield.material}
                  position={[0.119, -0.75, 0]}
                  rotation={[0.42, 0.08, -0.036]}
                />
                <mesh
                  name="Left_Leg_Shield_Bracket"
                  geometry={nodes.Left_Leg_Shield_Bracket.geometry}
                  material={nodes.Left_Leg_Shield_Bracket.material}
                  position={[0.119, -0.75, 0]}
                  rotation={[0.42, 0.08, -0.036]}
                />
                <mesh
                  name="Left_Leg_Shield_Bracket_2"
                  geometry={nodes.Left_Leg_Shield_Bracket_2.geometry}
                  material={nodes.Left_Leg_Shield_Bracket_2.material}
                  position={[0.119, -0.75, 0]}
                  rotation={[0.42, 0.08, -0.036]}
                />
                <mesh
                  name="Left_Leg_Shield_Bracket_3"
                  geometry={nodes.Left_Leg_Shield_Bracket_3.geometry}
                  material={nodes.Left_Leg_Shield_Bracket_3.material}
                  position={[0.119, -0.75, 0]}
                  rotation={[0.42, 0.08, -0.036]}
                />
                <mesh
                  name="Left_Leg_Shield_Bracket_4"
                  geometry={nodes.Left_Leg_Shield_Bracket_4.geometry}
                  material={nodes.Left_Leg_Shield_Bracket_4.material}
                  position={[0.119, -0.75, 0]}
                  rotation={[0.42, 0.08, -0.036]}
                />
                <mesh
                  name="Left_Leg_Shield_Bracket_Plate"
                  geometry={nodes.Left_Leg_Shield_Bracket_Plate.geometry}
                  material={nodes.Left_Leg_Shield_Bracket_Plate.material}
                  position={[0.119, -0.75, 0]}
                  rotation={[0.42, 0.08, -0.036]}
                />
                <mesh
                  name="Left_Leg_Shield_Bracket_Plate_2"
                  geometry={nodes.Left_Leg_Shield_Bracket_Plate_2.geometry}
                  material={nodes.Left_Leg_Shield_Bracket_Plate_2.material}
                  position={[0.119, -0.75, 0]}
                  rotation={[0.42, 0.08, -0.036]}
                />
                <mesh
                  name="Left_Leg_Shield_Bracket_Plate_3"
                  geometry={nodes.Left_Leg_Shield_Bracket_Plate_3.geometry}
                  material={nodes.Left_Leg_Shield_Bracket_Plate_3.material}
                  position={[0.119, -0.75, 0]}
                  rotation={[0.42, 0.08, -0.036]}
                />
                <mesh
                  name="Left_Leg_Shield_Bracket_Plate_4"
                  geometry={nodes.Left_Leg_Shield_Bracket_Plate_4.geometry}
                  material={nodes.Left_Leg_Shield_Bracket_Plate_4.material}
                  position={[0.119, -0.75, 0]}
                  rotation={[0.42, 0.08, -0.036]}
                />
              </group>
              <group name="Lower_Left_Leg" position={[0.119, -0.75, 0]}>
                <group name="Lower_Left_Leg_2">
                  <mesh
                    name="Left_Leg_2"
                    geometry={nodes.Left_Leg_2.geometry}
                    material={nodes.Left_Leg_2.material}
                    rotation={[-0.962, 0.05, 0.072]}
                  />
                </group>
                <group name="Lower_Left_Leg_3">
                  <mesh
                    name="Left_Leg_3"
                    geometry={nodes.Left_Leg_3.geometry}
                    material={nodes.Left_Leg_3.material}
                    rotation={[0.131, 0.087, -0.011]}
                  />
                </group>
                <group name="Left_Foot">
                  <group
                    name="leftFootLocator"
                    position={[0, 0, -0.219]}
                    rotation={[-1.305, -0.173, -1.228]}
                  >
                    <group name="leftFootLocator_1" scale={0.014} />
                  </group>
                  <mesh
                    name="Left_Foot_1"
                    geometry={nodes.Left_Foot_1.geometry}
                    material={nodes.Left_Foot_1.material}
                    rotation={[0, 0.087, 0]}
                  />
                </group>
              </group>
            </group>
            <group name="lowerLeftLegController" scale={0.013} />
            <group name="lowerRightLegController" scale={0.013} />
            <group
              name="leftFootController"
              position={[-0.376, 0.85, -0.819]}
              scale={0.013}
            />
            <group
              name="rightFootController"
              position={[0.275, 0.894, -0.824]}
              scale={0.013}
            />
            <group
              name="tailController"
              position={[0.875, 0.625, -0.125]}
              scale={0.013}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/proot.gltf')

export default KalkaProtogenModel
